apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: k8s-the-lawyer-world-tls
spec:
    secretName: k8s-the-lawyer-world
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: thelawyer.world
    dnsNames:
        - thelawyer.world
        - www.thelawyer.world
    acme:
        config:
            - http01:
                ingressClass: nginx
              domains:
                - thelawyer.world
                - www.thelawyer.world
