apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
meta:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: 'locnguyen1986@gmail.com'
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                ingress:
                    class:nginx
